In [6]:
import pandas as pd
import numpy as np

In [7]:
heart = pd.read_csv("heart.csv")
heart

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [8]:
air = pd.read_csv("stations.csv")
air

,id,station_code,city,state_code,pin_code,latitude,longitude,elevation_m,topo_complexity,coastal_proximity,valley_factor
0,1,DL01,Dwarka,DL,110078,28.610948,77.038456,215,0.7,0.000000,0.80
1,2,DL02,New Delhi,DL,110006,28.628191,77.241044,212,0.7,0.000000,0.80
2,3,DL03,Delhi,DL,110042,28.750815,77.116277,217,0.7,0.000000,0.90
3,4,CG01,Pawaras,CG,486865,18.388855,81.683361,212,0.5,0.370772,0.60
4,5,RJ01,Alwar,RJ,356172,27.550006,76.611703,286,0.3,0.000000,0.95
...,...,...,...,...,...,...,...,...,...,...,...
548,549,HR15,Satnali,HR,123024,28.369743,75.963402,296,0.6,0.000000,0.50
549,550,MH90,Pune,MH,438101,18.533400,73.811260,604,0.6,0.554518,0.40
550,551,TN37,Ranipet,TN,563060,12.962446,79.308470,194,0.4,0.561615,0.80
551,552,WB18,Durgapur,WB,752892,23.553915,87.282194,91,0.3,0.466164,0.60
552,553,WB19,Howrah,WB,793065,22.597360,88.305750,7,0.4,0.614145,0.95

In [9]:
air.isnull().sum()

id                   0
station_code         0
city                 0
state_code           0
pin_code             0
latitude             0
longitude            1
elevation_m          0
topo_complexity      0
coastal_proximity    0
valley_factor        0
dtype: int64

In [10]:
heart.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [11]:
air_clean = air.dropna()

heart_clean = heart.dropna()

In [12]:
air_clean.isnull().sum()

id                   0
station_code         0
city                 0
state_code           0
pin_code             0
latitude             0
longitude            0
elevation_m          0
topo_complexity      0
coastal_proximity    0
valley_factor        0
dtype: int64

In [13]:
heart_clean.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [15]:
part1 = air[['station_code', 'city']]

part2 = air[['latitude', 'longitude']]

In [16]:
integrated_air = pd.concat([part1, part2], axis=1)

integrated_air.head()

  station_code       city   latitude  longitude
0         DL01     Dwarka  28.610948  77.038456
1         DL02  New Delhi  28.628191  77.241044
2         DL03      Delhi  28.750815  77.116277
3         CG01    Pawaras  18.388855  81.683361
4         RJ01      Alwar  27.550006  76.611703

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

heart_scaled = heart_clean.copy()

numeric_cols = heart_scaled.select_dtypes(include=np.number).columns

heart_scaled[numeric_cols] = scaler.fit_transform(
    heart_scaled[numeric_cols]
)

heart_scaled.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,0.000000,0.708333,1.0,typical,0.481132,0.244292,1.0,1.0,0.603053,0.0,0.370968,1.0,0.000000,fixed,No
1,0.003322,0.791667,1.0,asymptomatic,0.622642,0.365297,0.0,1.0,0.282443,1.0,0.241935,0.5,1.000000,normal,Yes
2,0.006645,0.791667,1.0,asymptomatic,0.245283,0.235160,0.0,1.0,0.442748,1.0,0.419355,0.5,0.666667,reversable,Yes
3,0.009967,0.166667,1.0,nonanginal,0.339623,0.283105,0.0,0.0,0.885496,0.0,0.564516,1.0,0.000000,normal,No
4,0.013289,0.250000,0.0,nontypical,0.339623,0.178082,0.0,1.0,0.770992,0.0,0.225806,0.0,0.000000,normal,No

In [18]:
heart.duplicated().sum()

np.int64(0)

In [19]:
heart_corrected = heart.drop_duplicates()

heart_corrected.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [32]:
heart = heart.dropna()

In [33]:
X = heart.drop('AHD', axis=1)

X = pd.get_dummies(X, drop_first=True)

y = heart['AHD']

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=5000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8833333333333333