In [1]:
pip install requests beautifulsoup4 pandas lxml

Requirement already satisfied: requests in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (2.33.1)
Collecting beautifulsoup4
  Obtaining dependency information for beautifulsoup4 from https://files.pythonhosted.org/packages/1a/39/47f9197bdd44df24d67ac8893641e16f386c984a0619ef2ee4c51fbbc019/beautifulsoup4-4.14.3-py3-none-any.whl.metadata
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: pandas in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (3.0.2)
Collecting lxml
  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/f2/a7/0a915557538593cb1bbeedcd40e13c7a261822c26fecbbdb71dad0c2f540/lxml-6.1.0-cp312-cp312-win_amd64.whl.metadata
  Downloading lxml-6.1.0-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (from requests) (2026.1.4)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Obtaining dependency information for soupsieve>=1.6.1 from https://files.pythonhosted.org/packages/46/2c/1462b1d0a634697ae9e55b3cecdcb64788e8b7d63f54d923fcd0bb140aed/soupsieve-2.8.3-py3-none-any.whl.metadata
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\jay\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
   ---------------------------------------- 0.0/107.7 kB ? eta -:--:--
   ----------- ---------------------------- 30.7/107.7 kB ? eta -:--:--
   ----------- ---------------------------- 30.7/107.7 kB ? eta -:--:--
   ---------------------- ---------------- 61.4/107.7 kB 469.7 kB/s eta 0:00:01
   --------------------------------- ----- 92.2/107.7 kB 525.1 kB/s eta 0:00:01
   -------------------------------------- 107.7/107.7 kB 447.2 kB/s eta 0:00:00
Downloading lxml-6.1.0-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
    --------------------------------------- 0.1/4.0 MB 5.1 MB/s eta 0:00:01
   - -------------------------------------- 0.1/4.0 MB 3.2 MB/s eta 0:00:02
   -- ------------------------------------- 0.2/4.0 MB 1.8 MB/s eta 0:00:03
   --- ------------------------------------ 0.4/4.0 MB 2.5 MB/s eta 0:00:02
   ---- ----------------------------------- 0.5/4.0 MB 2.3 MB/s eta 0:00:02
   ------- -------------------------------- 0.8/4.0 MB 3.2 MB/s eta 0:00:02
   ---------- ----------------------------- 1.0/4.0 MB 3.4 MB/s eta 0:00:01
   -------------- ------------------------- 1.5/4.0 MB 4.3 MB/s eta 0:00:01
   ------------------ --------------------- 1.8/4.0 MB 4.6 MB/s eta 0:00:01
   ----------------------- ---------------- 2.3/4.0 MB 5.3 MB/s eta 0:00:01
   -------------------------------- ------- 3.2/4.0 MB 6.7 MB/s eta 0:00:01
   ------------------------------------- -- 3.7/4.0 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  4.0/4.0 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 6.9 MB/s eta 0:00:00
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, lxml, beautifulsoup4
Successfully installed beautifulsoup4-4.14.3 lxml-6.1.0 soupsieve-2.8.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://www.amazon.in/OnePlus-Charcoal-Snapdragon%C2%AE-Personalised-Game-Changing/dp/B0FZSWZZW2/ref=sr_1_2_sspa?crid=3102CCAZ0QYM7&dib=eyJ2IjoiMSJ9.o30eChCgzAqOpmi3bNL3ocx4gUs7LAab__TGYYEv-jf1wE2KMazAOGZLg1lqzkniJzskxBbzi4_rI91YXekEcSRbryzTQOs3JY8so6moOJprlO_mj2pZJDO-55v7Hego1Qnjm551tQUMj1O12A9qNckF-sJ70HH_EVkNFB31rrsyErTwVnEy1jebJh8ZhrvYnh9RVaWKQC7_7Hr_PexxuQRCwnfPThq4d6Up_YrWRA0.sXHFEX6ltYOcDhBBIJm53lZ9PEB8b6nxsZmOd0vGrPw&dib_tag=se&keywords=one%2Bplus%2B12r&qid=1778553116&sprefix=one%2Bplus%2B12%2Caps%2C485&sr=8-2-spons&aref=0xQ68m66KL&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1"

In [4]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9"
}

In [5]:
page = requests.get(url, headers=headers)

print(page.status_code)

200

In [6]:
soup = BeautifulSoup(page.content, "lxml")

In [7]:
customer_name = []
ratings = []
review_title = []
reviews = []

In [8]:
review_data = soup.find_all("div", {"data-hook": "review"})

In [9]:
for item in review_data:
    
    # Customer Name
    name = item.find("span", class_="a-profile-name")
    customer_name.append(name.text.strip() if name else "N/A")
    
    # Rating
    rating = item.find("i", {"data-hook": "review-star-rating"})
    ratings.append(rating.text.strip() if rating else "N/A")
    
    # Review Title
    title = item.find("a", {"data-hook": "review-title"})
    review_title.append(title.text.strip() if title else "N/A")
    
    # Review Text
    review = item.find("span", {"data-hook": "review-body"})
    reviews.append(review.text.strip() if review else "N/A")

In [10]:
data = pd.DataFrame({
    "Customer Name": customer_name,
    "Rating": ratings,
    "Review Title": review_title,
    "Review": reviews
})

In [11]:
data

       Customer Name            Rating Review Title Review
0    neeraj lakhotia  5 out of 5 stars          N/A    N/A
1                Ray  5 out of 5 stars          N/A    N/A
2              Varun  4 out of 5 stars          N/A    N/A
3            Monisha  5 out of 5 stars          N/A    N/A
4    Amazon Customer  5 out of 5 stars          N/A    N/A
5       Deepak Dubey  5 out of 5 stars          N/A    N/A
6  Shrikrishan Patel  5 out of 5 stars          N/A    N/A
7            Krishna  4 out of 5 stars          N/A    N/A
8                 Mj  5 out of 5 stars          N/A    N/A
9         Mhd mydeen  4 out of 5 stars          N/A    N/A

In [12]:
print(len(review_data))

10

In [13]:
data.to_csv("amazon_reviews.csv", index=False)

print("CSV File Saved Successfully")

CSV File Saved Successfully

In [14]:
data.head()

     Customer Name            Rating Review Title Review
0  neeraj lakhotia  5 out of 5 stars          N/A    N/A
1              Ray  5 out of 5 stars          N/A    N/A
2            Varun  4 out of 5 stars          N/A    N/A
3          Monisha  5 out of 5 stars          N/A    N/A
4  Amazon Customer  5 out of 5 stars          N/A    N/A

In [15]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer Name  10 non-null     str
 1   Rating         10 non-null     str
 2   Review Title   10 non-null     str
 3   Review         10 non-null     str
dtypes: str(4)
memory usage: 452.0 bytes

In [16]:
print("Total Reviews:", len(data))

Total Reviews: 10